const initialState = {
  name: "",
  id: "",
  age: "",
  telephone: "",
  department: "1",
  city: "",
  caso: 2,
  test: "si",
  testType: "antigenica",
  testLoaded: "si",
  testResult: "positivo",
  email: "",
  address: "",
  barrio: "",
  ocupation: "",
  priority: "5",
  testPlace: "presencial",
  startDate: new Date(),
  symptoms: "",
  risks: "",
  lastDate: new Date(),
  extras: "",
  from: "",
  appPassword: "",
  message: "Buen día \nadjunto le envío",
  subject: "",
  testDate: new Date(),
  ficha: "NO",
  cuidador: {
    id: "",
    name: ""
  },
  historiaClinica: "",
  ambulance: "",
  medico: {
    name: "",
    email: "",
    cellphone: "",
  },
  hcMessage: "",
};

export default initialState;